### ISSUE TITLE
Azure ServiceBus subscription suddenly not work

### ISSUE THREAD

**Issue by yangtiger0306** [Microsoft/azure-spring-boot#203]
Dear all:
We are using Azure Service Bus with topics/subscriptions by using this project code. The subscriptions are just  working well for a while (maybe one day or a few hours) and and it suddenly throws ' Unauthorized access.' exception.  We need to restart the application again and this issue will happen again. Does anyone can help us with this issue .Thanks a lot.

Error Log:
com.microsoft.azure.servicebus.primitives.AuthorizationFailedException: Unauthorized access. 'Listen' claim(s) are required to perform this operation. Resource: 'sb://servicebusdotcnnamespacedeveastasia.servicebus.windows.net/salesorderexpresstopic/subscriptions/salesorderexpresssubscription_servicelayer2'. TrackingId:387866c052944928bb9af6b54b5c130a_G9, SystemTracker:gateway6, Timestamp:10/3/2017 9:00:12 AM
        at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:50)
        at com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.onError(CoreMessageReceiver.java:716)
        at com.microsoft.azure.servicebus.primitives.CoreMessageReceiver.onClose(CoreMessageReceiver.java:867)
        at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.processOnClose(BaseLinkHandler.java:68)
        at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:42)
        at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
        at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307)
        at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:275)
        at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:426)
        at java.lang.Thread.run(Thread.java:748)

**Comment by yangtiger0306** [comment]
Problem is solved .

**Comment by NairRahulMohanan** [comment]
@yangtiger0306 Hi. I am facing the same issue. How did you solve it?
