### ISSUE TITLE
UnHandled exception while processing events in reactor

### ISSUE THREAD

**Issue by vangnd** [Microsoft/azure-spring-boot#235]
I am trying to create a example to using service bus and I get this error 

azure.servicebus.connection-string=Endpoint=sb://example-service-bus.servicebus.windows.net/;SharedAccessKeyName=RootManageSharedAccessKey;SharedAccessKey=XXhz1o5ixj84mahuanzUTHEldGUuiaH9Zddp/mG7YKc=
azure.servicebus.queue-name=vendor-message
azure.servicebus.queue-receive-mode=peeklock
azure.servicebus.topic-name=vendor
azure.servicebus.subscription-name=vendor-sub
azure.servicebus.subscription-receive-mode=peeklock

```

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.9.RELEASE)

2017-11-30 10:34:01.381  INFO 7143 --- [           main] com.jeppesen.Application                 : Starting Application on Vangs-MacBook-Pro.local with PID 7143 (/Users/vangnd1/Documents/workspace-sts-3.9.1.RELEASE/ServiceBusPOC/target/classes started by vangnd1 in /Users/vangnd1/Documents/workspace-sts-3.9.1.RELEASE/ServiceBusPOC)
2017-11-30 10:34:01.383  INFO 7143 --- [           main] com.jeppesen.Application                 : No active profile set, falling back to default profiles: default
2017-11-30 10:34:01.423  INFO 7143 --- [           main] ationConfigEmbeddedWebApplicationContext : Refreshing org.springframework.boot.context.embedded.AnnotationConfigEmbeddedWebApplicationContext@161b062a: startup date [Thu Nov 30 10:34:01 MST 2017]; root of context hierarchy
2017-11-30 10:34:02.262  INFO 7143 --- [           main] s.b.c.e.t.TomcatEmbeddedServletContainer : Tomcat initialized with port(s): 8080 (http)
2017-11-30 10:34:02.269  INFO 7143 --- [           main] o.apache.catalina.core.StandardService   : Starting service [Tomcat]
2017-11-30 10:34:02.269  INFO 7143 --- [           main] org.apache.catalina.core.StandardEngine  : Starting Servlet Engine: Apache Tomcat/8.5.23
2017-11-30 10:34:02.347  INFO 7143 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Spring embedded WebApplicationContext
2017-11-30 10:34:02.347  INFO 7143 --- [ost-startStop-1] o.s.web.context.ContextLoader            : Root WebApplicationContext: initialization completed in 927 ms
2017-11-30 10:34:02.460  INFO 7143 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'characterEncodingFilter' to: [/*]
2017-11-30 10:34:02.460  INFO 7143 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'hiddenHttpMethodFilter' to: [/*]
2017-11-30 10:34:02.460  INFO 7143 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'httpPutFormContentFilter' to: [/*]
2017-11-30 10:34:02.460  INFO 7143 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2017-11-30 10:34:02.461  INFO 7143 --- [ost-startStop-1] .s.DelegatingFilterProxyRegistrationBean : Mapping filter: 'springSecurityFilterChain' to: [/*]
2017-11-30 10:34:02.461  INFO 7143 --- [ost-startStop-1] o.s.b.w.servlet.ServletRegistrationBean  : Mapping servlet: 'dispatcherServlet' to [/]
2017-11-30 10:34:02.647  INFO 7143 --- [           main] c.m.a.s.primitives.MessagingFactory      : Creating messaging factory from connection string 'Endpoint=sb://example-service-bus.servicebus.windows.net/;EntityPath=vendor-message;'
2017-11-30 10:34:02.660  INFO 7143 --- [           main] c.m.a.s.primitives.MessagingFactory      : Creating and starting reactor
2017-11-30 10:34:02.674  INFO 7143 --- [           main] c.m.a.s.primitives.MessagingFactory      : Started reactor
2017-11-30 10:34:02.675  INFO 7143 --- [95-706b9026d6e1] c.m.a.s.primitives.MessagingFactory      : starting reactor instance.
2017-11-30 10:34:02.690  INFO 7143 --- [95-706b9026d6e1] c.m.a.s.primitives.MessagingFactory      : Creating connection to host 'example-service-bus.servicebus.windows.net:5671'
2017-11-30 10:35:18.234 ERROR 7143 --- [95-706b9026d6e1] c.m.a.s.primitives.MessagingFactory      : UnHandled exception while processing events in reactor:
2017-11-30 10:35:18.234 ERROR 7143 --- [95-706b9026d6e1] c.m.a.s.primitives.MessagingFactory      : UnHandled exception while processing events in reactor:

org.apache.qpid.proton.engine.HandlerException: java.lang.IllegalArgumentException
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:112) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276) ~[proton-j-0.13.1.jar:na]
	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:448) ~[azure-servicebus-1.0.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: java.lang.IllegalArgumentException: null
	at java.nio.Buffer.position(Buffer.java:244) ~[na:1.8.0_131]
	at org.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.pop(SimpleSslTransportWrapper.java:411) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.engine.impl.ssl.SslImpl$UnsecureClientAwareTransportWrapper.pop(SslImpl.java:185) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.engine.impl.TransportImpl.pop(TransportImpl.java:1476) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.reactor.impl.SelectorImpl.select(SelectorImpl.java:145) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.reactor.impl.IOHandler.handleQuiesced(IOHandler.java:57) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:381) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.engine.BaseHandler.onReactorQuiesced(BaseHandler.java:87) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:206) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.13.1.jar:na]
	... 4 common frames omitted

2017-11-30 10:35:18.244 ERROR 7143 --- [95-706b9026d6e1] c.m.a.s.primitives.MessagingFactory      : Reactor error occured

com.microsoft.azure.servicebus.primitives.ServiceBusException: java.lang.IllegalArgumentException, TrackingId: e3b8b0bb-e303-462e-b64f-067939067d6f, at: 2017-11-30T10:35:18.241-07:00[America/Denver]
	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:470) ~[azure-servicebus-1.0.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_131]
Caused by: java.lang.IllegalArgumentException: null
	at java.nio.Buffer.position(Buffer.java:244) ~[na:1.8.0_131]
	at org.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.pop(SimpleSslTransportWrapper.java:411) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.engine.impl.ssl.SslImpl$UnsecureClientAwareTransportWrapper.pop(SslImpl.java:185) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.engine.impl.TransportImpl.pop(TransportImpl.java:1476) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.reactor.impl.SelectorImpl.select(SelectorImpl.java:145) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.reactor.impl.IOHandler.handleQuiesced(IOHandler.java:57) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:381) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.engine.BaseHandler.onReactorQuiesced(BaseHandler.java:87) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:206) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276) ~[proton-j-0.13.1.jar:na]
	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:448) ~[azure-servicebus-1.0.0.jar:na]
	... 1 common frames omitted

2017-11-30 10:35:18.248  WARN 7143 --- [           main] ationConfigEmbeddedWebApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'application': Unsatisfied dependency expressed through field 'queueClient'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'queueClient' defined in class path resource [com/microsoft/azure/spring/autoconfigure/servicebus/ServiceBusAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.microsoft.azure.servicebus.QueueClient]: Factory method 'queueClient' threw exception; nested exception is com.microsoft.azure.servicebus.primitives.ServiceBusException: java.lang.IllegalArgumentException, TrackingId: e3b8b0bb-e303-462e-b64f-067939067d6f, at: 2017-11-30T10:35:18.241-07:00[America/Denver]
2017-11-30 10:35:18.250  INFO 7143 --- [           main] o.apache.catalina.core.StandardService   : Stopping service [Tomcat]
2017-11-30 10:35:18.263  INFO 7143 --- [           main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-11-30 10:35:18.271 ERROR 7143 --- [           main] o.s.boot.SpringApplication               : Application startup failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'application': Unsatisfied dependency expressed through field 'queueClient'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'queueClient' defined in class path resource [com/microsoft/azure/spring/autoconfigure/servicebus/ServiceBusAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.microsoft.azure.servicebus.QueueClient]: Factory method 'queueClient' threw exception; nested exception is com.microsoft.azure.servicebus.primitives.ServiceBusException: java.lang.IllegalArgumentException, TrackingId: e3b8b0bb-e303-462e-b64f-067939067d6f, at: 2017-11-30T10:35:18.241-07:00[America/Denver]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:588) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:366) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1264) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:553) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:197) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:761) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:867) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:543) ~[spring-context-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.boot.context.embedded.EmbeddedWebApplicationContext.refresh(EmbeddedWebApplicationContext.java:122) ~[spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:693) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:360) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:303) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.9.RELEASE.jar:1.5.9.RELEASE]
	at com.jeppesen.Application.main(Application.java:38) [classes/:na]
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'queueClient' defined in class path resource [com/microsoft/azure/spring/autoconfigure/servicebus/ServiceBusAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.microsoft.azure.servicebus.QueueClient]: Factory method 'queueClient' threw exception; nested exception is com.microsoft.azure.servicebus.primitives.ServiceBusException: java.lang.IllegalArgumentException, TrackingId: e3b8b0bb-e303-462e-b64f-067939067d6f, at: 2017-11-30T10:35:18.241-07:00[America/Denver]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:599) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1173) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1067) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:513) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:483) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:306) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:302) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:202) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:208) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1066) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:585) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	... 19 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.microsoft.azure.servicebus.QueueClient]: Factory method 'queueClient' threw exception; nested exception is com.microsoft.azure.servicebus.primitives.ServiceBusException: java.lang.IllegalArgumentException, TrackingId: e3b8b0bb-e303-462e-b64f-067939067d6f, at: 2017-11-30T10:35:18.241-07:00[America/Denver]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:189) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:588) ~[spring-beans-4.3.13.RELEASE.jar:4.3.13.RELEASE]
	... 31 common frames omitted
Caused by: com.microsoft.azure.servicebus.primitives.ServiceBusException: java.lang.IllegalArgumentException, TrackingId: e3b8b0bb-e303-462e-b64f-067939067d6f, at: 2017-11-30T10:35:18.241-07:00[America/Denver]
	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:470) ~[azure-servicebus-1.0.0.jar:na]
	at java.lang.Thread.run(Thread.java:748) ~[na:1.8.0_131]
Caused by: java.lang.IllegalArgumentException: null
	at java.nio.Buffer.position(Buffer.java:244) ~[na:1.8.0_131]
	at org.apache.qpid.proton.engine.impl.ssl.SimpleSslTransportWrapper.pop(SimpleSslTransportWrapper.java:411) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.engine.impl.ssl.SslImpl$UnsecureClientAwareTransportWrapper.pop(SslImpl.java:185) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.engine.impl.TransportImpl.pop(TransportImpl.java:1476) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.reactor.impl.SelectorImpl.select(SelectorImpl.java:145) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.reactor.impl.IOHandler.handleQuiesced(IOHandler.java:57) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.reactor.impl.IOHandler.onUnhandled(IOHandler.java:381) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.engine.BaseHandler.onReactorQuiesced(BaseHandler.java:87) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:206) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307) ~[proton-j-0.13.1.jar:na]
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:276) ~[proton-j-0.13.1.jar:na]
	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:448) ~[azure-servicebus-1.0.0.jar:na]
	... 1 common frames omitted
```

**Comment by vangnd** [comment]
network issue
