### ISSUE TITLE
Not able to avoid require SEND privileges on endpoint with current azure-service-bus-java dependency

### ISSUE THREAD

**Issue by stianborgesen** [Microsoft/azure-spring-boot#316]
## Environment
- Spring boot starter:
  - service bus spring boot starter

  
- OS Type: MacOS
- Java version: 
  - 1.8

## Summary
Issue from [azure-service-bus-java](https://github.com/Azure/azure-service-bus-java) causing the following error when trying to listen, and NOT send to endpoint

> Unauthorized access. 'Send' claim(s) are required to perform this operation. 

Please update azure-service-bus-java dependency to a version where the [issue](https://github.com/Azure/azure-service-bus-java/issues/110#event-1276620463) is fixed. Looking at issue close date of this issue, it a fix is hopefully included in later releases

## Reproduce steps
1. Create service bus endpoint with only listen privileges
2. Create QueueClient with this endpoint
3. Run application

## Expected Results
Access without needing privileges to send on queue

## Actual Results
Error starting ApplicationContext. To display the conditions report re-run your application with 'debug' enabled.
2018-04-13 15:08:35.354 ERROR 97247 --- [           main] o.s.boot.SpringApplication               : Application run failed

org.springframework.beans.factory.UnsatisfiedDependencyException: Error creating bean with name 'application': Unsatisfied dependency expressed through field 'queueClient'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'queueClient' defined in class path resource [xxx/xxx/xxx/xxx/xxx/ServiceBusAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.microsoft.azure.servicebus.QueueClient]: Factory method 'queueClient' threw exception; nested exception is com.microsoft.azure.servicebus.primitives.AuthorizationFailedException: Unauthorized access. 'Send' claim(s) are required to perform this operation. Resource: 'sb://xxxxxx'. TrackingId:1a0fecf9aa7ea14f_G29, SystemTracker:gateway9, xxx 1:08:35 PM, errorContext[NS: esb-test-sbn.servicebus.windows.net, PATH: xxx, REFERENCE_ID: 1bfaa2_1a0fecf3a3aa7ea14f_G29]
	at org.springframework.beans.factory.anxxxtation.AutowiredAnxxxtationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnxxxtationBeanPostProcessor.java:587)
	at org.springframework.beans.factory.anxxxtation.InjectionMetadata.inject(InjectionMetadata.java:91)
	at org.springframework.beans.factory.anxxxtation.AutowiredAnxxxtationBeanPostProcessor.postProcessPropertyValues(AutowiredAnxxxtationBeanPostProcessor.java:373)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.populateBean(AbstractAutowireCapableBeanFactory.java:1344)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:578)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:760)
	at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:869)
	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:550)
	at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:140)
	at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:759)
	at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:395)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:327)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1255)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1243)
	at xxx.xxx.xxx.xxx.xxx.Application.main(Application.java:48)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'queueClient' defined in class path resource [xxx/xxx/xxx/xxx/xxx/ServiceBusAutoConfiguration.class]: Bean instantiation via factory method failed; nested exception is org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.microsoft.azure.servicebus.QueueClient]: Factory method 'queueClient' threw exception; nested exception is com.microsoft.azure.servicebus.primitives.AuthorizationFailedException: Unauthorized access. 'Send' claim(s) are required to perform this operation. Resource: 'sb://xxxxxx'. TrackingId:a14f_G29, SystemTracker:gateway9, xxx 1:08:35 PM, errorContext[NS: esb-test-sbn.servicebus.windows.net, PATH: xxx, REFERENCE_ID: 1bfaa2_1a0fecf29aa7ea14f_G29]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:587)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateUsingFactoryMethod(AbstractAutowireCapableBeanFactory.java:1250)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1099)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:541)
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:501)
	at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:317)
	at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:228)
	at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:315)
	at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
	at org.springframework.beans.factory.config.DependencyDescriptor.resolveCandidate(DependencyDescriptor.java:251)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1138)
	at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:1065)
	at org.springframework.beans.factory.anxxxtation.AutowiredAnxxxtationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnxxxtationBeanPostProcessor.java:584)
	... 19 common frames omitted
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.microsoft.azure.servicebus.QueueClient]: Factory method 'queueClient' threw exception; nested exception is com.microsoft.azure.servicebus.primitives.AuthorizationFailedException: Unauthorized access. 'Send' claim(s) are required to perform this operation. Resource: 'sb://xxxxxx'. TrackingId:1a0feda7ea14f_G29, SystemTracker:gateway9, xxx 1:08:35 PM, errorContext[NS: esb-test-sbn.servicebus.windows.net, PATH: xxx, REFERENCE_ID: 1bfaa2_1a0fecf3a4f_G29]
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185)
	at org.springframework.beans.factory.support.ConstructorResolver.instantiateUsingFactoryMethod(ConstructorResolver.java:579)
	... 31 common frames omitted
Caused by: com.microsoft.azure.servicebus.primitives.AuthorizationFailedException: Unauthorized access. 'Send' claim(s) are required to perform this operation. Resource: 'sb://xxxxxx'. TrackingId:1a0fec4d90629a4f_G29, SystemTracker:gateway9, xxx 1:08:35 PM, errorContext[NS: esb-test-sbn.servicebus.windows.net, PATH: xxx, REFERENCE_ID: 1bfaa2_1a7e4629ea14f_G29]
	at com.microsoft.azure.servicebus.primitives.ExceptionUtil.toException(ExceptionUtil.java:50)
	at com.microsoft.azure.servicebus.primitives.CoreMessageSender.onClose(CoreMessageSender.java:413)
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.processOnClose(BaseLinkHandler.java:68)
	at com.microsoft.azure.servicebus.amqp.BaseLinkHandler.onLinkRemoteClose(BaseLinkHandler.java:42)
	at org.apache.qpid.proton.engine.BaseHandler.handle(BaseHandler.java:176)
	at org.apache.qpid.proton.engine.impl.EventImpl.dispatch(EventImpl.java:108)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.dispatch(ReactorImpl.java:307)
	at org.apache.qpid.proton.reactor.impl.ReactorImpl.process(ReactorImpl.java:275)
	at com.microsoft.azure.servicebus.primitives.MessagingFactory$RunReactor.run(MessagingFactory.java:448)
	at java.lang.Thread.run(Thread.java:745)

**Comment by sophiaso** [comment]
Hi @stianborgesen, great to see opening issue with detailed info provided, will upgrade the  azure-service-bus-java dependency to a fixed version.

**Comment by stianborgesen** [comment]
Thank you Sophiaso. Is this fix included in version 2.0.2 or 2.0.3? If not do you know when it will be included?

**Comment by sophiaso** [comment]
Hi @stianborgesen, it's already released as version [2.0.3](http://search.maven.org/#search%7Cga%7C1%7Cg%3A%22com.microsoft.azure%22%20AND%20a%3A%22azure-servicebus-spring-boot-starter%22), thanks.
