### ISSUE TITLE
HTTP Response Code 403 while running the sample azure-active-directory-spring-boot-sample 

### ISSUE THREAD

**Issue by kaykumar** [microsoft/azure-spring-boot#383]
## Environment
- Spring boot starter:
    - active directory spring boot starter
  
- OS Type: MacOS
- Java version: 
  - 1.8
 
## Summary
1: Go to azure portal -- > 

https://portal.azure.com/#blade/Microsoft_AAD_IAM/ActiveDirectoryMenuBlade/RegisteredApps

2: Add a new application 
3: set  "oauth2AllowImplicitFlow": true in manifest file
4: create a key under settings
5: Add reply url http://localhost:8080

Configure the sample application "sample azure-active-directory-spring-boot-sample " as described in sample doc

## Reproduce steps

1: Go to localhost:8080
it will perform a SSO with Azure portal
2: It will be unable to load the authorities logging this into the logs:

java.io.IOException: Server returned HTTP response code: 403 for URL: https://graph.windows.net/me/memberOf?api-version=1.6
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876) ~[na:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[na:1.8.0_121]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[na:1.8.0_121]
	at com.microsoft.azure.spring.autoconfigure.aad.AzureADGraphClient.getResponseStringFromConn(AzureADGraphClient.java:72) ~[azure-spring-boot-2.0.4-SNAPSHOT.jar:na]
	at com.microsoft.azure.spring.autoconfigure.aad.AzureADGraphClient.getUserMembershipsV1(AzureADGraphClient.java:59) ~[azure-spring-boot-2.0.4-SNAPSHOT.jar:na]
	at com.microsoft.azure.spring.autoconfigure.aad.AzureADGraphClient.loadUserGroups(AzureADGraphClient.java:87) ~[azure-spring-boot-2.0.4-SNAPSHOT.jar:na]
	at com.microsoft.azure.spring.autoconfigure.aad.AzureADGraphClient.getGroups(AzureADGraphClient.java:83) ~[azure-spring-boot-2.0.4-SNAPSHOT.jar:na]
	at com.microsoft.azure.spring.autoconfigure.aad.AADAuthenticationFilter.doFilterInternal(AADAuthenticationFilter.java:77) ~[azure-spring-boot-2.0.4-SNAPSHOT.jar:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:100) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]

## Expected Results
Authorities should be loaded 

## Actual Results

java.io.IOException: Server returned HTTP response code: 403 for URL: https://graph.windows.net/me/memberOf?api-version=1.6
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1876) ~[na:1.8.0_121]
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1474) ~[na:1.8.0_121]
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:254) ~[na:1.8.0_121]
	at com.microsoft.azure.spring.autoconfigure.aad.AzureADGraphClient.getResponseStringFromConn(AzureADGraphClient.java:72) ~[azure-spring-boot-2.0.4-SNAPSHOT.jar:na]
	at com.microsoft.azure.spring.autoconfigure.aad.AzureADGraphClient.getUserMembershipsV1(AzureADGraphClient.java:59) ~[azure-spring-boot-2.0.4-SNAPSHOT.jar:na]
	at com.microsoft.azure.spring.autoconfigure.aad.AzureADGraphClient.loadUserGroups(AzureADGraphClient.java:87) ~[azure-spring-boot-2.0.4-SNAPSHOT.jar:na]
	at com.microsoft.azure.spring.autoconfigure.aad.AzureADGraphClient.getGroups(AzureADGraphClient.java:83) ~[azure-spring-boot-2.0.4-SNAPSHOT.jar:na]
	at com.microsoft.azure.spring.autoconfigure.aad.AADAuthenticationFilter.doFilterInternal(AADAuthenticationFilter.java:77) ~[azure-spring-boot-2.0.4-SNAPSHOT.jar:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:116) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:100) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:66) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:105) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:56) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:334) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:215) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:178) ~[spring-security-web-5.0.4.RELEASE.jar:5.0.4.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:357) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]
	at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:270) ~[spring-web-5.0.5.RELEASE.jar:5.0.5.RELEASE]

**Comment by GauravWable** [comment]
Same problem.. Did anyone solved this issue ?

**Comment by MykolaDekhtiarenko** [comment]
Same problem

**Comment by MykolaDekhtiarenko** [comment]
@kaykumar, probably that is because you haven't chosen "Access the directory as sign-in user" in DELEGATED PERMISSIONS section. You should come it, press "Save", press "Grant permissions"

**Comment by GauravWable** [comment]
I was trying to access these APIs from Postman and other Application. The given sample maintains the session for logged in user. I have updated WebSecurityConfig file to disable sessions and that worked.

**WebSecurityConfig.java**
    @Configuration
    @EnableWebSecurity
    public class WebSecurityConfig extends WebSecurityConfigurerAdapter {

	@Autowired
	private AADAuthenticationFilter aadAuthFilter;

	@Override
	protected void configure(HttpSecurity http) throws Exception {

		// Stateless session for APIs
		http.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS);

		// Disable Cookies
		http.csrf().disable().authorizeRequests()
			.antMatchers("/api/v1_Annonymous/SensorModuleInternalAPI").permitAll()
			.antMatchers("/api/v1/**").authenticated() // request matcher for authenticate user, Authenticated user can access all apis
			.and().httpBasic();

		// Add Active Directory filter
		http.addFilterBefore(aadAuthFilter, UsernamePasswordAuthenticationFilter.class);

	}

    }

**Comment by markvr** [comment]
Is there anyway to use this library without needing to be an AAD admin?  I guess either by prompting the user for consent, or populating the user groups in the claim that is returned without needing to query the graph API afterwards?

Requiring all applications to be approved by an AAD admin limits the usefulness of this somewhat.

**Comment by mkirbach** [comment]
I also got the following error message after logging into the demo application:

Server returned HTTP response code: 403 for URL: https://graph.windows.net/me/memberOf?api-version=1.6

The Demo App Azure AD user had a group assignment as suggested in the readme file.

The error above was due to the missing right of the Microsoft Graph API (within the Azure AD Demo App) to read all groups. After granting this right to the API, everything does work.

**Comment by blacelle** [comment]
For the record, the role is: "Group.Read.All" withing "Microsoft Graph"

**Comment by mahoekst** [comment]
Not working for me either. I tried adding the suggested permissions and grant them as admin. Still 403 error.

**Comment by berndgoetz** [comment]
> 
> 
> I was trying to access these APIs from Postman and other Application. The given sample maintains the session for logged in user. I have updated WebSecurityConfig file to disable sessions and that worked.
> 
> **WebSecurityConfig.java**
> @configuration
> @EnableWebSecurity
> public class WebSecurityConfig extends WebSecurityConfigurerAdapter {
> 
> ```
> @Autowired
> private AADAuthenticationFilter aadAuthFilter;
> 
> @Override
> protected void configure(HttpSecurity http) throws Exception {
> 
> 	// Stateless session for APIs
> 	http.sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS);
> 
> 	// Disable Cookies
> 	http.csrf().disable().authorizeRequests()
> 		.antMatchers("/api/v1/**").authenticated() // request matcher for authenticate user, Authenticated user can access all apis
> 		.and().httpBasic();
> 
> 	// Add Active Directory filter
> 	http.addFilterBefore(aadAuthFilter, UsernamePasswordAuthenticationFilter.class);
> 
> }
> 
> }
> ```

I tried your configuration but that fails with 

`Caused by: java.lang.NoClassDefFoundError: javax/xml/bind/JAXBException
	at com.microsoft.applicationinsights.internal.config.JaxbAppInsightsConfigurationBuilder.build(JaxbAppInsightsConfigurationBuilder.java:49) ~[applicationinsights-core-2.2.0.jar:na]
`

Moreover, I don't understand what that change should have to do with the fact that a group definition is mandatory. And therefore the permission "Group.Read.All" within "Microsoft Graph".

**Comment by einue** [comment]
Sorry for opening this again, but I remain the same error.

And to be more precise I get the exception : "Failed to map group to authorities."

spring-boot-version: v2.1.4.RELEASE
azure-version: 2.1.6

I added the microsoft graph permissons on the app-registration to the ad and set some properties to read the user and its groups.
permissions:
Read all groups
delegeted permissions:
Sign in and read user profile
Read all groups
Sign in and read user profile 
Sign users in

Is there anything missing?

The Exception is thrown in the Method getResponseStringFromConn(HttpURLConnection conn) from AzureADGraphClient.

I hope you can help me. Since I spend already a lot of time in choosing the right versions of the dependencies to get the app working....

**Comment by TimGundmann** [comment]
I get the same error.

**Comment by einue** [comment]
@TimGundmann Finally I get it‘s working. You have to set the permissions on the Microsoft Graph as described above. Don‘t forget to explicitly push the button „Grant permissions“ and make sure that during this Operation no error is thrown.

https://msdnshared.blob.core.windows.net/media/2018/05/image117.png

**Comment by lhanson** [comment]
I'm also unable to use `azure-active-directory-spring-boot-starter` to access my own data since I don't have `Group.Read.All` permissions.

Am I misunderstanding something, or is it the case that this starter is only usable for Active Directory admins?

**Comment by lhanson** [comment]
Until/unless somebody at Microsoft can provide guidance, I've created a [branch](https://github.com/lhanson/azure-spring-boot/tree/memberof-403) which works around this issue by catching the HTTP 403 response to the `me/memberOf` request and simply populating a granted authority of `ROLE_USER` in that case. I should probably log that as well, to help troubleshoot possible authz issues down the road.

Maybe I'll submit a PR once I use it myself a bit more, but any feedback or suggestions are welcome.

**Comment by blacelle** [comment]
We used to rely on the role "Group.Read.All" within "Microsoft Graph".

But recently, we observed it does not work properly anymore, but the following role fixed the 403 issue: 'Member.Read.Hidden'

**Comment by blacelle** [comment]
It seems the proper role is now 'Directory.Read.All'
https://docs.microsoft.com/en-us/graph/api/user-list-memberof?view=graph-rest-1.0&tabs=javascript

**Comment by lhanson** [comment]
I think many of us would still like to be able to use `azure-spring-boot` without requiring tenant-wide read permissions via `*.All` permissions.

**Comment by sammycakes** [comment]
I've found that in the azure spring boot sample, in file TodolistController.java, in order to POST to path /api/todolist, the user needs to have access to group1.

so I had to add the user I was signing in as to group "group1" in the Azure portal. I did this by going into my Azure portal (portal.azure.com), go to 'Azure Active Directory' on the left-hand side, click "Users", click the user who I'm authorizing with into the to-do list app, then clicking "Groups" and "+Add" and adding "group1" to that user. Now I am able to add items to the to-do list.

**Comment by ramya25** [comment]
@kaykumar Are you sure you followed all the steps in the https://github.com/microsoft/azure-spring-boot/blob/master/azure-spring-boot-samples/azure-active-directory-spring-boot-sample/README.md.
I followed the above steps and the sample worked fine. Please make sure you followed all the steps in the Readme for your existing app. If you are unsure, try creating a new app following all the steps in Readme and revert with relevant error details if you are still facing issues.

**Comment by lhanson** [comment]
@ramya25 Can you comment on the issue many of us are having with this library being unusable without admin consent via `Directory.Read.All`? As non-administrators or members of organizations unwilling or unable to grant such broad permissions to users' apps, is there no way to use the Graph API to access our own data?

https://github.com/microsoft/azure-spring-boot/issues/383#issuecomment-422969692

**Comment by ramya25** [comment]
@lhanson Sure, will look into it if it is possible to access user's own data without admin consent and update you. By the way, the required permission mentioned in sample README.md is `Directory.AccessAsUser.All`
not `Directory.Read.All`

**Comment by olavgg** [comment]
Is there any difference between `Directory.AccessAsUser.All` and `User.Read` permissions?
Our Azure AD Admin has only assigned the `User.Read` permission for our app.

**Comment by ramya25** [comment]
@olavgg yes there is difference between those two permissions. `User.Read` is a simple permission which doesn't need admin consent and this allows user to sign-in and read/view the user profile. `Directory.AccessAsUser.All ` can access the directory resources same as the signed-in user so its needs admin consent. For further details you can refer [directory permissions](https://docs.microsoft.com/en-us/graph/permissions-reference#directory-permissions)

**Comment by benc-uk** [comment]
Wow this has been open for a year!?

There has to be a way to configure this without needing to read the groups the user is in. When I use Node.js and .NET with Azure AD I need no such permissions.
Requiring these permissions is pretty much a show stopper

How can we tell Spring to ignore user groups entirely?

**Comment by lhanson** [comment]
@benc-uk @ramya25 I'm still not convinced that requiring admin approval to discover what groups I belong to (or to access anything under `/me`, for that matter) when I can do the same by simply logging into the outlook web app isn't a fundamentally broken API design. That seems to leave the door open to workarounds like "fork the `azure-spring-boot` library to simply scrape outlook.office.com to discover what groups I belong to", which I'm sure we can all agree is a bad idea.

In the meantime I have [patched](https://github.com/lhanson/azure-spring-boot/commit/dc540ae4e7e7f93232d31aaf25d6c91663865e5e) the client to not explode for us peasants who don't have `Directory.AccessUser.All`. I'd be happy to submit a PR to make this a more user-friendly library but I was kind of hoping to hear something definitive one way or the other from somebody at MS about the "correct" approach they're advocating for.

**Comment by benc-uk** [comment]
The challenge is two fold:
- I've worked with the ADAL/MSAL libraries for authentication with both server side JS (Node), client side JS, Python and .NET - none of them try to access the user group information, they all work perfectly well with just `User.Read`. But the concept of *Roles* seems hard baked into the Spring security framework so someone has decided to populate that using Azure AD groups. 
- I don't think we'll change the minds of the Azure AD team on what scopes and permissions in Azure AD require admin access or not.

**Comment by neuqlz** [comment]
If you encounter this problem, it must be a permission problem, please check the permission granted configuration in AAD -> App Registrations ->  your registration -> API Permissions. Basically Microsoft Graph: Directory.AccessAsUser.All and User.Read are needed.

**Comment by mahoekst** [comment]
> If you encounter this problem, it must be a permission problem, please check the permission granted configuration in AAD -> App Registrations -> your registration -> API Permissions. Basically Microsoft Graph: Directory.AccessAsUser.All and User.Read are needed.

Directory.AccessAsUser.All  is a permission which needs admin consent. What is the reason for this permission? This is typically to much for an application to have.

**Comment by abdhafid** [comment]
You need add this permission : 
Microsoft Graph :
Directory.AccessAsUser.All : Delegated : Access directory as the signed in user : Yes
![azuread_grant](https://user-images.githubusercontent.com/32271996/77859519-3c972800-720a-11ea-8953-88889f027b3f.png)

**Comment by trs80** [comment]
> You need add this permission to Microsoft Graph :
> ![azuread_grant](https://user-images.githubusercontent.com/32271996/77859519-3c972800-720a-11ea-8953-88889f027b3f.png)

Which clearly says that admin consent is required, which is what we're complaining about. I found the uservoice for this, it's been open for 4 years with the last update 2 years ago so I wouldn't hold my breath. Do upvote it though, it's basically all you can do https://microsoftgraph.uservoice.com/forums/920506-microsoft-graph-feature-requests/suggestions/15969922-add-a-my-groups-read-write-permission-that-do

**Comment by trs80** [comment]
Also there's [getMemberGroups](https://docs.microsoft.com/en-us/graph/api/user-getmembergroups?view=graph-rest-1.0&tabs=http) which only needs User.ReadBasic.All and GroupMember.Read.All, the latter still requires admin consent but at least it's not as broad as Directory.AccessAsUser.All
