### ISSUE TITLE
Application can't read new messages form Service Bus queue

### ISSUE THREAD

**Issue by olgakorichkovskaya** [Microsoft/azure-spring-boot#589]
The issue is similar to https://github.com/Microsoft/azure-spring-boot/issues/343 but can't be solved by upgrading to v1.2.8 due to incomputability of with version of Spring Boot.

## Environment
- Spring boot starter:  
  - spring-boot-starter: 1.5.8.RELEASE
  - service bus spring boot starter: 0.2.0
  
- OS Type: Windows/CentOS
- Java version: 
  - 1.8

## Summary
Client of Service Bus stops consuming messages from queue.
It occurs after a network problem (when client temporary can't connect to Azure) - for instance lack of internet. **When Internet connection is back, Azure SDK is not able to establish connection to Azure Service Bus again.**
logs there are many similar exceptions:

```
Sending CBS Token for amqp://URL/queue_name failed.

java.lang.IllegalStateException: Operation not allowed after the com.microsoft.azure.servicebus.primitives.RequestResponseLink instance is Closed.
	at com.microsoft.azure.servicebus.primitives.ClientEntity.throwIfClosed(ClientEntity.java:130)
	at com.microsoft.azure.servicebus.primitives.RequestResponseLink.requestAysnc(RequestResponseLink.java:216)
	at com.microsoft.azure.servicebus.primitives.CommonRequestResponseOperations.sendCBSTokenAsync(CommonRequestResponseOperations.java:81)
	at com.microsoft.azure.servicebus.primitives.MessagingFactory.lambda$sendSASTokenAndSetRenewTimer$2(MessagingFactory.java:539)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:952)
	... 6 common frames omitted
Wrapped by: java.util.concurrent.CompletionException: java.lang.IllegalStateException: Operation not allowed after the com.microsoft.azure.servicebus.primitives.RequestResponseLink instance is Closed.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
```

## Reproduce steps

1. Connect Client to Azure Service Bus, connection is sussesfull, no problems with consuming.
2. Sender sends messages to the queue.
3. There are some temporary connection problem (lack of internet connection)
4. Internet is back, but client can not connect to SB and consume messages.

## Expected Results
Client consumes messages from the queue all the time without any problems, event after temporary conenction problem can resume consuming.

## Actual Results
Application stop consuming messages, looks like nothing to consume. In logs all the time:
```
	Will retry sending CBS Token for amqp://url/queue_name after 5 seconds.
 c.m.a.s.primitives.CoreMessageReceiver   : No messages received from 'queue_name'. Pending receive request timed out. Returning null to the client.
 c.m.a.s.primitives.RequestResponseLink   : Request with id:request:620 timed out
 282364 --- [onPool-worker-3] c.m.a.s.primitives.MessagingFactory      : Sending CBS Token for amqp://url/queue_name failed.

java.util.concurrent.CompletionException: com.microsoft.azure.servicebus.primitives.TimeoutException: Request timed out.
	at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:292)
	at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:308)
	at java.util.concurrent.CompletableFuture.uniCompose(CompletableFuture.java:943)
	at java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:926)
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474)
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977)
```
After client application restart, client is able to establish connection to Azure and continue consuming messages.

Problem can be reproduced on local dev environment.

**Additional context**
Queue settings:
Message time to live: 14 days
Lock duration: 2 mins
Duplicate detection history: 10
Maximum Delivery Count: 3
ENABLE PARTITIONING: false

Client:
queue-receive-mode=peeklock
Java 8

**Comment by warrenzhu25** [comment]
Thanks for reporting this issue. What do you mean by `1.2.8`  incompatibility of Spring Boot?

Another suggestion for this is you can try https://github.com/Microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-samples/servicebus-queue-binder-sample or https://github.com/Microsoft/spring-cloud-azure/tree/master/spring-cloud-azure-samples/servicebus-topic-binder-sample. This library provides high level abstraction and better user experience.

**Comment by olgakorichkovskaya** [comment]
Hi @warrenzhu25,

I am using Spring Boot  1.5.8.RELEASE and have no chance to move to Spring Boot 2 in near future.
Also azure-servicebus-spring-boot-starter version 0.2.0 is used.
It contains 
azure-spring-boot-starter  0.2.0, and it use spring-boot-starter 1.5.4.RELEASE
maximum  version of azure-spring-boot-starter **not** for Spring Boot 2 is  0.2.4 and it is compatible with Spring Boot 1.5.11.RELEASE - it means for me upgrade of Spring Boot. But 0.2.4 contains 
azure-servicebus  1.2.5 - in this version this bug is not fixed.

According to https://github.com/Microsoft/azure-spring-boot/issues/343, bug is fixed since 1.2.8
I'll show in table view to make it easy to read:

| Spring Boot  | azure-servicebus-spring-boot-starter | azure-servicebus | Comment|
| ------------- |:-------------:| -----:|-----:|
| 1.5.8.RELEASE    | 0.2.0 | 1.0.0 |  I use currently |
| 1.5.11.RELEASE  | 0.2.4 |  1.2.5 | Maximum version I can upgrade  | 
| 2.1.0.RELEASE    | 2.1.4 |    1.2.5 | The last version for now (28.02.19), but still doesn't have fix of this bug |

**It would be perfect for me to have azure-servicebus-spring-boot-starter in v 0.2.* (compatable with Spring Boot 1.5.*) with dependency to azure-servicebus 1.2.8.**

Thanks for suggestion for another library.

The last stable version of spring-cloud-azure-dependencies » 1.0.0.M2 has 1.2.5 only.
And com.microsoft.azure spring-cloud-starter-azure-servicebus has only release candidate  1.1.0.RC3

Maybe  in  future I will migrate for these.

**Comment by Incarnation-p-lee** [comment]
@olgakorichkovskaya 
Thanks for collection and summary the information. We can add the request to our next sprint plan, and try to upgrade 0.2.0 servicebus sdk to 1.2.8 if there is no compatibility issue between 1.2.8 and spring 1.5.x.
