### ISSUE TITLE
spring-boot-starter-azure 2.12 and spring boot 2.1.3.RELEASE issue 

### ISSUE THREAD

**Issue by jaimodha** [microsoft/azure-spring-boot#650]
## Environment
- Spring boot starter:
  
  - active directory spring boot starter
  
- OS Type: Windows/Linux/MacOS
- Java version: 
  
  - 1.8
  

## Summary

com.microsoft.azure:azure-active-directory-spring-boot-starter (v2.1.2) when used with the latest 2.1.3.RELEASE of spring boot fails in the authentication flow. All the steps are followed from this document. https://docs.microsoft.com/en-us/java/azure/spring-framework/configure-spring-boot-starter-java-app-with-azure-active-directory?view=azure-java-stable
 
## Reproduce steps

Just run the spring boot app with vwersion 2.1.3.RELEASE and com.microsoft.azure:azure-active-directory-spring-boot-starter (v2.1.2) the app fails in the authentication flow.

## Expected Results

The app should successfully complete the authentication flow.

## Actual Results

The app fails with the following error stack shown below

2019-04-03 13:38:50.564  WARN 20074 --- [nio-8080-exec-1] o.a.c.util.SessionIdGeneratorBase        : Creation of SecureRandom instance for session ID generation using [SHA1PRNG] took [206] milliseconds.
2019-04-03 13:39:14.689  INFO 20074 --- [pool-1-thread-1] c.m.aad.adal4j.AuthenticationAuthority   : [Correlation ID: 379e5783-3cfc-403c-b6e8-a247aadfeed5] Instance discovery was successful
2019-04-03 13:39:14.712 ERROR 20074 --- [pool-1-thread-1] c.m.aad.adal4j.AuthenticationContext     : [Correlation ID: 379e5783-3cfc-403c-b6e8-a247aadfeed5] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed.

java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at com.nimbusds.oauth2.sdk.util.URLUtils.serializeParameters(URLUtils.java:101) ~[oauth2-oidc-sdk-6.0.jar:6.0]
	at com.microsoft.aad.adal4j.AdalTokenRequest.toOAuthRequest(AdalTokenRequest.java:159) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:85) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:928) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47) ~[adal4j-1.6.0.jar:1.6.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]

2019-04-03 13:39:15.779  INFO 20074 --- [pool-2-thread-1] c.m.aad.adal4j.AuthenticationAuthority   : [Correlation ID: b0b8dfba-9052-4cc8-b2af-9b2eaadfeed5] Instance discovery was successful
2019-04-03 13:39:15.779 ERROR 20074 --- [pool-2-thread-1] c.m.aad.adal4j.AuthenticationContext     : [Correlation ID: b0b8dfba-9052-4cc8-b2af-9b2eaadfeed5] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed.

java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at com.nimbusds.oauth2.sdk.util.URLUtils.serializeParameters(URLUtils.java:101) ~[oauth2-oidc-sdk-6.0.jar:6.0]
	at com.microsoft.aad.adal4j.AdalTokenRequest.toOAuthRequest(AdalTokenRequest.java:159) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:85) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:928) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47) ~[adal4j-1.6.0.jar:1.6.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]

2019-04-03 13:39:21.628  INFO 20074 --- [pool-3-thread-1] c.m.aad.adal4j.AuthenticationAuthority   : [Correlation ID: d5e98c1b-c899-4cd4-8b1d-fbb6aadfeed5] Instance discovery was successful
2019-04-03 13:39:21.629 ERROR 20074 --- [pool-3-thread-1] c.m.aad.adal4j.AuthenticationContext     : [Correlation ID: d5e98c1b-c899-4cd4-8b1d-fbb6aadfeed5] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed.

java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at com.nimbusds.oauth2.sdk.util.URLUtils.serializeParameters(URLUtils.java:101) ~[oauth2-oidc-sdk-6.0.jar:6.0]
	at com.microsoft.aad.adal4j.AdalTokenRequest.toOAuthRequest(AdalTokenRequest.java:159) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:85) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:928) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47) ~[adal4j-1.6.0.jar:1.6.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]

2019-04-03 13:39:24.482  INFO 20074 --- [pool-4-thread-1] c.m.aad.adal4j.AuthenticationAuthority   : [Correlation ID: 463d604f-b947-4217-ba09-f23aaadfeed5] Instance discovery was successful
2019-04-03 13:39:24.482 ERROR 20074 --- [pool-4-thread-1] c.m.aad.adal4j.AuthenticationContext     : [Correlation ID: 463d604f-b947-4217-ba09-f23aaadfeed5] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed.

java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at com.nimbusds.oauth2.sdk.util.URLUtils.serializeParameters(URLUtils.java:101) ~[oauth2-oidc-sdk-6.0.jar:6.0]
	at com.microsoft.aad.adal4j.AdalTokenRequest.toOAuthRequest(AdalTokenRequest.java:159) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:85) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:928) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47) ~[adal4j-1.6.0.jar:1.6.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]

2019-04-03 13:39:25.598  INFO 20074 --- [pool-5-thread-1] c.m.aad.adal4j.AuthenticationAuthority   : [Correlation ID: efc548a5-dc94-45d3-9555-7d5eaadfeed5] Instance discovery was successful
2019-04-03 13:39:25.599 ERROR 20074 --- [pool-5-thread-1] c.m.aad.adal4j.AuthenticationContext     : [Correlation ID: efc548a5-dc94-45d3-9555-7d5eaadfeed5] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed.

java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at com.nimbusds.oauth2.sdk.util.URLUtils.serializeParameters(URLUtils.java:101) ~[oauth2-oidc-sdk-6.0.jar:6.0]
	at com.microsoft.aad.adal4j.AdalTokenRequest.toOAuthRequest(AdalTokenRequest.java:159) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:85) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:928) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47) ~[adal4j-1.6.0.jar:1.6.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]

2019-04-03 13:39:26.367  INFO 20074 --- [pool-6-thread-1] c.m.aad.adal4j.AuthenticationAuthority   : [Correlation ID: 7c6d1a8d-ebd1-474f-b7e3-42cbaadfeed5] Instance discovery was successful
2019-04-03 13:39:26.368 ERROR 20074 --- [pool-6-thread-1] c.m.aad.adal4j.AuthenticationContext     : [Correlation ID: 7c6d1a8d-ebd1-474f-b7e3-42cbaadfeed5] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed.

java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at com.nimbusds.oauth2.sdk.util.URLUtils.serializeParameters(URLUtils.java:101) ~[oauth2-oidc-sdk-6.0.jar:6.0]
	at com.microsoft.aad.adal4j.AdalTokenRequest.toOAuthRequest(AdalTokenRequest.java:159) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:85) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:928) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47) ~[adal4j-1.6.0.jar:1.6.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]

2019-04-03 13:39:27.121  INFO 20074 --- [pool-7-thread-1] c.m.aad.adal4j.AuthenticationAuthority   : [Correlation ID: b965bd50-3fc0-4d63-be52-2deeaadfeed5] Instance discovery was successful
2019-04-03 13:39:27.121 ERROR 20074 --- [pool-7-thread-1] c.m.aad.adal4j.AuthenticationContext     : [Correlation ID: b965bd50-3fc0-4d63-be52-2deeaadfeed5] Execution of class com.microsoft.aad.adal4j.AcquireTokenCallable failed.

java.lang.ClassCastException: java.lang.String cannot be cast to java.util.List
	at com.nimbusds.oauth2.sdk.util.URLUtils.serializeParameters(URLUtils.java:101) ~[oauth2-oidc-sdk-6.0.jar:6.0]
	at com.microsoft.aad.adal4j.AdalTokenRequest.toOAuthRequest(AdalTokenRequest.java:159) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AdalTokenRequest.executeOAuthRequestAndProcessResponse(AdalTokenRequest.java:85) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AuthenticationContext.acquireTokenCommon(AuthenticationContext.java:928) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:70) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AcquireTokenCallable.execute(AcquireTokenCallable.java:38) ~[adal4j-1.6.0.jar:1.6.0]
	at com.microsoft.aad.adal4j.AdalCallable.call(AdalCallable.java:47) ~[adal4j-1.6.0.jar:1.6.0]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [na:1.8.0_171]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [na:1.8.0_171]
	at java.lang.Thread.run(Thread.java:748) [na:1.8.0_171]

**Comment by Incarnation-p-lee** [comment]
Thanks for issue this, looks like known issue. But could you please share your correctly information about our starter version ? I think 2.12 is not valid version.

**Comment by jaimodha** [comment]
Attaching the build file here so that shows all the version here 

```
plugins {
	id 'org.springframework.boot' version '2.1.3.RELEASE'
	id 'java'
}

apply plugin: 'io.spring.dependency-management'

group = 'com.modhajai'
version = '0.0.1-SNAPSHOT'
sourceCompatibility = '1.8'

repositories {
	mavenCentral()
}

ext {
	set('azureVersion', '2.1.2')
}

dependencies {
	implementation 'com.microsoft.azure:azure-active-directory-spring-boot-starter'
	implementation 'com.microsoft.azure:azure-spring-boot-starter'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
}

dependencyManagement {
	imports {
		mavenBom "com.microsoft.azure:azure-spring-boot-bom:${azureVersion}"
	}
}
```

**Comment by Incarnation-p-lee** [comment]
@jaimodha

Could you have a try to add below dependency to your build file, you may need to convert to gradle format.

```
        <dependency>
            <groupId>com.nimbusds</groupId>
            <artifactId>oauth2-oidc-sdk</artifactId>
            <version>5.64.4</version>
        </dependency>
```

**Comment by jaimodha** [comment]
@Incarnation-p-lee Thanks for that info after adding that dependency it worked. So will that cause any concern in future if we upgrade to future versions of spring security and spring boot since we are adding the specific version of that dependency. Or the future version of spring boot starter azure fix this?

**Comment by Incarnation-p-lee** [comment]
Good to know that. Actually it should be the dependency conflict from azure aad sdk, details see this issue:

https://github.com/AzureAD/azure-activedirectory-library-for-java/issues/248

We are planing to upgrade this and you may have no concern about the explicit version management.

**Comment by lu-cheng** [comment]
Any update on this issue?

**Comment by lu-cheng** [comment]
Any update on this issue?

**Comment by ZoltanV** [comment]
I had the same error when using wrong version combos.
Fix the issue with:
**2.3.1.RELEASE** **spring-boot-starter-parent** version
and
**2.3.5** **azure-spring-boot-bom** version
```
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>2.3.1.RELEASE</version>
        <relativePath/> <!-- lookup parent from repository -->
    </parent>

    <properties>
        ...
        <azure.version>2.3.5</azure.version>
    </properties>

    <dependencies>
        ...
	<dependency>
            <groupId>com.microsoft.azure</groupId>
            <artifactId>azure-keyvault-secrets-spring-boot-starter</artifactId>
        </dependency>
    </dependencies>

    <dependencyManagement>
        <dependencies>
            <dependency>
                <groupId>com.microsoft.azure</groupId>
                <artifactId>azure-spring-boot-bom</artifactId>
                <version>${azure.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>
        </dependencies>
    </dependencyManagement>
```

**Comment by chenrujun** [comment]
We have change the groupId and artifactId. Could you please try new groupId and artifactId?

Refs:
1. https://github.com/Azure/azure-sdk-for-java/blob/master/sdk/spring/azure-spring-boot-starter-keyvault-secrets/CHANGELOG.md#233-2020-08-13
2. https://github.com/Azure/azure-sdk-for-java/tree/master/sdk/spring/azure-spring-boot-starter-keyvault-secrets#include-the-package

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
