### ISSUE TITLE
Pageable support in DocumentDB

### ISSUE THREAD

**Issue by zhzy0077** [Microsoft/azure-spring-boot#82]
I am using the following code to try pageable:
```java
@SpringBootApplication
public class DemoApplication {

    public static void main(String[] args) {
        SpringApplication.run(DemoApplication.class, args);
    }

    @Bean
    public CommandLineRunner init(UserRepository repository) {
        return (args) -> {
            repository.deleteAll();
            for (int i = 0; i < 100; i++) {
                repository.save(new User(String.valueOf(i), "firstName", "lastName"));
            }
            System.out.println(repository.findAll(new PageRequest(1, 10)));
        };
    }

}
```
Then I get exceptions as `java.lang.UnsupportedOperationException: findAll(Pageable pageable) not supported yet.`.

The whole logs are:
```

  .   ____          _            __ _ _
 /\\ / ___'_ __ _ _(_)_ __  __ _ \ \ \ \
( ( )\___ | '_ | '_| | '_ \/ _` | \ \ \ \
 \\/  ___)| |_)| | | | | || (_| |  ) ) ) )
  '  |____| .__|_| |_|_| |_\__, | / / / /
 =========|_|==============|___/=/_/_/_/
 :: Spring Boot ::        (v1.5.6.RELEASE)

2017-08-02 15:01:55.009  INFO 19780 --- [           main] com.example.demo.DemoApplication         : Starting DemoApplication on Zhiyuan-Work with PID 19780 (C:\Users\t-zhzhe\Desktop\demo\target\classes started by t-zhzhe in C:\Users\t-zhzhe\Desktop\demo)
2017-08-02 15:01:55.014  INFO 19780 --- [           main] com.example.demo.DemoApplication         : No active profile set, falling back to default profiles: default
2017-08-02 15:01:55.152  INFO 19780 --- [           main] s.c.a.AnnotationConfigApplicationContext : Refreshing org.springframework.context.annotation.AnnotationConfigApplicationContext@61009542: startup date [Wed Aug 02 15:01:55 CST 2017]; root of context hierarchy
2017-08-02 15:01:58.834  INFO 19780 --- [           main] c.m.azure.documentdb.DocumentClient      : Initializing DocumentClient with serviceEndpoint [https://spring.documents.azure.com:443/], ConnectionPolicy [ConnectionPolicy [requestTimeout=60, mediaRequestTimeout=300, connectionMode=Gateway, mediaReadMode=Buffered, maxPoolSize=100, idleConnectionTimeout=60, userAgentSuffix=;;azure-documentdb-spring-boot-starter/0.1.4;b283874abd22954131daae5647d03ae3395d9f6e753089e4837e80fdbe0c2b92, retryOptions=com.microsoft.azure.documentdb.RetryOptions@5cc69cfe, enableEndpointDiscovery=true, preferredLocations=null]], ConsistencyLevel [Session]
2017-08-02 15:02:00.978  INFO 19780 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Registering beans for JMX exposure on startup
2017-08-02 15:02:01.863  INFO 19780 --- [           main] c.m.a.d.internal.ServiceJNIWrapper       : Microsoft.Azure.Documents.ServiceInterop.dll exists in working directory.
2017-08-02 15:02:01.863  INFO 19780 --- [           main] c.m.a.d.internal.ServiceJNIWrapper       : DocumentDB.Spatial.Sql.dll exists in working directory.
2017-08-02 15:02:01.868  INFO 19780 --- [           main] c.m.a.d.internal.ServiceJNIWrapper       : ServiceJNI has loaded.
2017-08-02 15:02:10.069  INFO 19780 --- [           main] utoConfigurationReportLoggingInitializer : 

Error starting ApplicationContext. To display the auto-configuration report re-run your application with 'debug' enabled.
2017-08-02 15:02:10.082 ERROR 19780 --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Failed to execute CommandLineRunner
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:735) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.callRunners(SpringApplication.java:716) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.afterRefresh(SpringApplication.java:703) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1118) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1107) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	at com.example.demo.DemoApplication.main(DemoApplication.java:17) [classes/:na]
Caused by: java.lang.UnsupportedOperationException: findAll(Pageable pageable) not supported yet.
	at com.microsoft.azure.spring.data.documentdb.repository.support.SimpleDocumentDbRepository.findAll(SimpleDocumentDbRepository.java:72) ~[spring-data-azure-documentdb-0.1.4.jar:na]
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:1.8.0_131]
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[na:1.8.0_131]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:1.8.0_131]
	at java.lang.reflect.Method.invoke(Method.java:498) ~[na:1.8.0_131]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.executeMethodOn(RepositoryFactorySupport.java:504) ~[spring-data-commons-1.13.6.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.doInvoke(RepositoryFactorySupport.java:489) ~[spring-data-commons-1.13.6.RELEASE.jar:na]
	at org.springframework.data.repository.core.support.RepositoryFactorySupport$QueryExecutorMethodInterceptor.invoke(RepositoryFactorySupport.java:461) ~[spring-data-commons-1.13.6.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:56) ~[spring-data-commons-1.13.6.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92) ~[spring-aop-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.data.repository.core.support.SurroundingTransactionDetectorMethodInterceptor.invoke(SurroundingTransactionDetectorMethodInterceptor.java:57) ~[spring-data-commons-1.13.6.RELEASE.jar:na]
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179) ~[spring-aop-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:213) ~[spring-aop-4.3.10.RELEASE.jar:4.3.10.RELEASE]
	at com.sun.proxy.$Proxy47.findAll(Unknown Source) ~[na:na]
	at com.example.demo.DemoApplication.lambda$init$0(DemoApplication.java:28) [classes/:na]
	at org.springframework.boot.SpringApplication.callRunner(SpringApplication.java:732) [spring-boot-1.5.6.RELEASE.jar:1.5.6.RELEASE]
	... 6 common frames omitted

2017-08-02 15:02:10.083  INFO 19780 --- [           main] s.c.a.AnnotationConfigApplicationContext : Closing org.springframework.context.annotation.AnnotationConfigApplicationContext@61009542: startup date [Wed Aug 02 15:01:55 CST 2017]; root of context hierarchy
2017-08-02 15:02:10.086  INFO 19780 --- [           main] o.s.j.e.a.AnnotationMBeanExporter        : Unregistering JMX-exposed beans on shutdown
```

**Comment by rajadilipkolli** [comment]
While fixing this care should be taken about sorting

**Comment by yungez** [comment]
close this one since spring data documentdb is moved to https://github.com/Microsoft/spring-data-documentdb
