### ISSUE TITLE
Avoid AADAppRoleStatelessAuthenticationFilter autoconfiguration

### ISSUE THREAD

**Issue by Gaboxondo** [microsoft/azure-spring-boot#856]
Hi all.

I have a problem with the AADAppRoleStatelessAuthenticationFilter autoconfiguration.
The post is in stackoverflow so i will copy paste here to avoid writing it to times:

https://stackoverflow.com/questions/60874517/spring-boot-azuread-filter-autoconfiguration

I few days ago I was able to configure the integration with Azure AD and spring boot.
I'm usisng the following dependencies to achieve that:

```

        <dependency>
         	<groupId>org.springframework.security</groupId>
		<artifactId>spring-security-oauth2-client</artifactId>
	</dependency>
	<dependency>
		<groupId>com.microsoft.azure</groupId>
		<artifactId>azure-active-directory-spring-boot-starter</artifactId>
	</dependency>
	<dependency>
		<groupId>com.microsoft.azure</groupId>
		<artifactId>msal4j</artifactId>
	</dependency>
</dependencies>
```

It works so nice and I was able to get the expected result, but now the problem.
I have to Security configurations. Each one are configured with spring profiles, for example:

```
spring:
  profiles:
    active: DDBBSecurized, local
```

This one enables the sucurity with DDBB and it was configuired before the integration with AzureAD, It works perfect

I also have 

```
spring:
  profiles:
    active: ADDSecurized, local
```

that enables the integration of azure AD.

Before configuring Azure AD integration if I use DDBBSecurized it works nice and I also had a option that if I dont configure anyThing. spring.profiles.active: local, for example, it disable the security:

the way to achive that is the following:

```
@EnableWebSecurity
@Profile( "DDBBSecurized" )
public class DDBBSecurityConfig extends WebSecurityConfigurerAdapter {

    @Autowired
    private RestAuthenticationExceptionHandler restAuthenticationExceptionHandler;

    @Override
    protected void configure(HttpSecurity http) throws Exception {

        http.csrf().disable().sessionManagement().sessionCreationPolicy( SessionCreationPolicy.STATELESS );
        http.headers().frameOptions().disable();

        //Filtro de autenticacion de peticiones
        http.addFilterAfter( new JWTAuthenticationFilter(), UsernamePasswordAuthenticationFilter.class );

        //Filtros CORS
        http.addFilterBefore( new CorsFilter(), ChannelProcessingFilter.class );

        //Manejador de excpeciones de login
        http.exceptionHandling().authenticationEntryPoint( restAuthenticationExceptionHandler );

        //Configuracion Endpoints
        http.authorizeRequests().antMatchers( HttpMethod.POST, "/auth/login**" ).permitAll()
            .antMatchers( "/v2/api-docs", "/configuration/**","/swagger*/**","/webjars/**" ).permitAll()
            .antMatchers( "/actuator/**" ).permitAll()
            .anyRequest().authenticated();
    }
}
```

I have my own JWT filter and login endpoint and I also had:

```
@EnableWebSecurity
@Profile( "!DDBBSecurized & !AzureAdSecurized" )
public class NonSecurityConfig extends WebSecurityConfigurerAdapter {

    @Autowired
    private RestAuthenticationExceptionHandler restAuthenticationExceptionHandler;

    @Override
    protected void configure(HttpSecurity http) throws Exception {

        http.csrf().disable().sessionManagement().sessionCreationPolicy( SessionCreationPolicy.STATELESS );
        http.headers().frameOptions().disable();

        //Filtros CORS
        http.addFilterBefore( new CorsFilter(), ChannelProcessingFilter.class );

        //Manejador de excpeciones de login
        http.exceptionHandling().authenticationEntryPoint( restAuthenticationExceptionHandler );

        //Configuracion Endpoints
        http.authorizeRequests().anyRequest().permitAll();
    }
}
```
That works Perfect.

Now If i use ADDSecurized everything works perfect.

```
@EnableWebSecurity
@Profile("AzureAdSecurized")
public class AzureSecurityConfig extends WebSecurityConfigurerAdapter {

    @Autowired
    private RestAuthenticationExceptionHandler restAuthenticationExceptionHandler;

    @Autowired
    private AADAppRoleStatelessAuthenticationFilter aadAuthenticationFilter;

    @Override
    protected void configure(HttpSecurity http) throws Exception {

        http.csrf().disable().sessionManagement().sessionCreationPolicy( SessionCreationPolicy.STATELESS );
        http.headers().frameOptions().disable();

        //Filtro de autenticacion de peticiones
        http.addFilterAfter( aadAuthenticationFilter, UsernamePasswordAuthenticationFilter.class );
        http.addFilterAfter( new AzureTokenGetFilter(), UsernamePasswordAuthenticationFilter.class );

        //Filtros CORS
        http.addFilterBefore( new CorsFilter(), ChannelProcessingFilter.class );

        //Manejador de excpeciones de login
        http.exceptionHandling().authenticationEntryPoint( restAuthenticationExceptionHandler );

        //Configuracion Endpoints
        http.authorizeRequests().antMatchers( HttpMethod.POST,  "/auth/login**" ).permitAll()
            .antMatchers( "/v2/api-docs", "/configuration/**", "/swagger*/**", "/webjars/**" ).permitAll()
            .antMatchers( "/actuator/**" ).permitAll().anyRequest().authenticated();
    }
}
```

But if I change to DDBBSecurized profile it is still passing the aadAuthenticationFilter filter of azure. even if this configuration is disable. It seems its autoconfigure and WebSecurityAdpater by its Own or something like That.

the properties I also have are:

```
security:
    oauth2:
      client:
        registration:
          azure:
            client-id: XXXX-XXXX-XXXX-XXXX-XXXXXXXX

azure:
  activedirectory:
    tenant-id: XXXX-XXXX-XXXX-XXXX-XXXXXXXX
    client-id: XXXX-XXXX-XXXX-XXXX-XXXXXXXX
    scope: /User.Read
    session-stateless: true
    authority-url: https://login.microsoftonline.com/
```

Now for example I have configured DDBBSecurized And I can see in the log that the filter is being applied:

STARTUPLOG:

```
2020-03-26 20:10:02,279 INFO class=org.springframework.boot.StartupInfoLogger  Starting Application on gggarrido10 with PID 8760 (D:\Proyectos\EvoSago\SOM-Back\admin-user\target\classes started by gggarrido in D:\Proyectos\EvoSago\SOM-Back)
2020-03-26 20:10:11,378 INFO class=org.springframework.boot.SpringApplication  The following profiles are active: DDBBSecurized,local
2020-03-26 20:10:31,479 INFO class=org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker  Bean 'org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration' of type [org.springframework.transaction.annotation.ProxyTransactionManagementConfiguration$$EnhancerBySpringCGLIB$$2e0e67bf] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
2020-03-26 20:10:33,267 INFO class=org.springframework.boot.web.embedded.tomcat.TomcatWebServer  Tomcat initialized with port(s): 8080 (http)
2020-03-26 20:10:34,434 INFO class=org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext  Root WebApplicationContext: initialization completed in 22895 ms
2020-03-26 20:10:39,649 INFO class=org.springframework.boot.actuate.endpoint.web.ServletEndpointRegistrar  Registered '/actuator/jolokia' to jolokia-actuator-endpoint
2020-03-26 20:10:42,925 INFO class=org.springframework.boot.actuate.endpoint.web.EndpointLinksResolver  Exposing 17 endpoint(s) beneath base path '/actuator'
2020-03-26 20:10:43,850 INFO class=org.springframework.security.web.DefaultSecurityFilterChain  Creating filter chain: any request, [es.indra.som.common.utilities.CorsFilter@26f5e45d, org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter@704c3bdf, org.springframework.security.web.context.SecurityContextPersistenceFilter@1e6d30c0, org.springframework.security.web.header.HeaderWriterFilter@5529522f, org.springframework.security.web.authentication.logout.LogoutFilter@4d2f9e3c, es.indra.som.security.filter.JWTAuthenticationFilter@37986daf, org.springframework.security.web.savedrequest.RequestCacheAwareFilter@69d667a5, org.springframework.security.web.servletapi.SecurityContextHolderAwareRequestFilter@7ab1ad9, org.springframework.security.web.authentication.AnonymousAuthenticationFilter@c82d925, org.springframework.security.web.session.SessionManagementFilter@1b60d324, org.springframework.security.web.access.ExceptionTranslationFilter@43a59289, org.springframework.security.web.access.intercept.FilterSecurityInterceptor@61993d18]
2020-03-26 20:10:45,610 INFO class=org.springframework.scheduling.concurrent.ExecutorConfigurationSupport  Initializing ExecutorService 'applicationTaskExecutor'
2020-03-26 20:10:48,503 INFO class=org.springframework.scheduling.concurrent.ExecutorConfigurationSupport  Initializing ExecutorService
2020-03-26 20:10:51,398 INFO class=org.springframework.boot.web.embedded.tomcat.TomcatWebServer  Tomcat started on port(s): 8080 (http) with context path ''
2020-03-26 20:10:51,407 INFO class=org.springframework.boot.StartupInfoLogger  Started Application in 53.341 seconds (JVM running for 56.018)
```

ERROR LOG BECAUSE THE ADD FILTER IS BEING APPLIED WHEN IT SHOULD'T

```
2020-03-26 20:11:16,144 ERROR class=com.microsoft.azure.spring.autoconfigure.aad.AADAppRoleStatelessAuthenticationFilter  Failed to initialize UserPrincipal.
com.nimbusds.jose.proc.BadJOSEException: Signed JWT rejected: Another algorithm expected, or no matching key(s) found
	at com.nimbusds.jwt.proc.DefaultJWTProcessor.process(DefaultJWTProcessor.java:384)
	at com.nimbusds.jwt.proc.DefaultJWTProcessor.process(DefaultJWTProcessor.java:330)
	at com.nimbusds.jwt.proc.DefaultJWTProcessor.process(DefaultJWTProcessor.java:321)
	at com.microsoft.azure.spring.autoconfigure.aad.UserPrincipalManager.buildUserPrincipal(UserPrincipalManager.java:83)
	at com.microsoft.azure.spring.autoconfigure.aad.AADAppRoleStatelessAuthenticationFilter.doFilterInternal(AADAppRoleStatelessAuthenticationFilter.java:58)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:166)
	at org.springframework.boot.actuate.web.trace.servlet.HttpTraceFilter.doFilterInternal(HttpTraceFilter.java:88)
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119)
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:193)
	at org.apache.catalina.core.ApplicationFilterChain.doFilter
```

The point is that before only with DDBBSecurized and NoSecurity ot works perfect. Why for ADDfilter even if I disable it by profile is appliying the filter?

I also tried to 

```
@SpringBootApplication(exclude = {SecurityAutoConfiguration.class , SecurityFilterAutoConfiguration.class,
	AADAuthenticationFilterAutoConfiguration.class})
```

I also tried to delete the full AzureSecurityConfiguration.... but it didnt work, event if I delete the full class it pass the filter

But it did not work and also the app doesnt start because it need AADAuthenticationFilterAutoConfiguration to autoconfigure the filters provided by the library with the properties set in applicacion.yaml avoid the user to manually configure them.

Thanks in advance.

**Comment by saragluna** [comment]
Thanks for reaching out. How about trying to put the AAD related configs into a file called `application-AzureAdSecurized.properties`? In which case these properties will only be available when the AAD profile enabled.

**Comment by Gaboxondo** [comment]
Hi @saragluna . Unfortunately I cant do that, because of the arquitecture of the app. The application runs taking an external configuration file and in this case it is not possible to run the app by using -Dspring.profile.active :(, I's a pity I know :(

**Comment by saragluna** [comment]
Then how is the profile set to the application?

**Comment by Gaboxondo** [comment]
We only have one application.yaml file in which we set spring.profiles.active= DDBBSecurized, local, ... I said that in the post I think

**Comment by Gaboxondo** [comment]
Also the configuration is provided with helm to kubernetes kluster....

**Comment by Gaboxondo** [comment]
some news about this?

**Comment by Gaboxondo** [comment]
I think I have a solution.

When defining the DDBBSecurized configuration I has add the following:

```
@EnableWebSecurity
@Profile( "DDBBSecurized" )
public class DDBBSecurityConfig extends WebSecurityConfigurerAdapter {

    @Autowired
    private RestAuthenticationExceptionHandler restAuthenticationExceptionHandler;

    @Bean
    public FilterRegistrationBean registration(AADAppRoleStatelessAuthenticationFilter filter) {
        FilterRegistrationBean registration = new FilterRegistrationBean(filter);
        registration.setEnabled(false);
        return registration;
    }

    @Override
    protected void configure(HttpSecurity http) throws Exception {

        http.csrf().disable().sessionManagement().sessionCreationPolicy( SessionCreationPolicy.STATELESS );
        http.headers().frameOptions().disable();

        //Filtro de autenticacion de peticiones
        http.addFilterBefore( new JWTAuthenticationFilter(), UsernamePasswordAuthenticationFilter.class );

        //Filtros CORS
        http.addFilterBefore( new CorsFilter(), ChannelProcessingFilter.class );

        //Manejador de excpeciones de login
        http.exceptionHandling().authenticationEntryPoint( restAuthenticationExceptionHandler );

        //Configuracion Endpoints
        http.authorizeRequests().antMatchers( HttpMethod.POST, "/auth/login**" ).permitAll()
            .antMatchers( "/v2/api-docs", "/configuration/**","/swagger*/**","/webjars/**" ).permitAll()
            .antMatchers( "/actuator/**" ).permitAll()
            .anyRequest().authenticated();
    }
}
```

What I am doing is manually disabling the regsitration of the filter that is automatically configured because of the definition of azure.activedirectory.client-id property.

I have to do some test yet but It will be nice another aproach to be able to disable that not with properties because otherwise it doesn't make much sense to define an AddFilterBefore if the bean is automatically created and applied in WebSecurityConfigurerAdapter as is explained, because anyway it is going to apply the filter even if I dont add this line

```
@EnableWebSecurity
@Profile("AzureAdSecurized")
public class AzureSecurityConfig extends WebSecurityConfigurerAdapter {

    @Autowired
    private RestAuthenticationExceptionHandler restAuthenticationExceptionHandler;

    @Autowired
    private AADAppRoleStatelessAuthenticationFilter aadAuthenticationFilter;

    @Override
    protected void configure(HttpSecurity http) throws Exception {

        http.csrf().disable().sessionManagement().sessionCreationPolicy( SessionCreationPolicy.STATELESS );
        http.headers().frameOptions().disable();

        //Filtro de autenticacion de peticiones
        http.addFilterBefore( aadAuthenticationFilter, UsernamePasswordAuthenticationFilter.class );
        http.addFilterBefore( new AzureTokenGetFilter(), UsernamePasswordAuthenticationFilter.class );

        //Filtros CORS
        http.addFilterBefore( new CorsFilter(), ChannelProcessingFilter.class );

        //Manejador de excpeciones de login
        http.exceptionHandling().authenticationEntryPoint( restAuthenticationExceptionHandler );

        //Configuracion Endpoints
        http.authorizeRequests().antMatchers( HttpMethod.POST,  "/auth/login**" ).permitAll()
            .antMatchers( "/v2/api-docs", "/configuration/**", "/swagger*/**", "/webjars/**" ).permitAll()
            .antMatchers( "/actuator/**" ).permitAll().anyRequest().authenticated();
    }
}
```

**Comment by Gaboxondo** [comment]
Now I have a new problem.
I have two divide the api two apply two different filters depending on the path, so the "trick" to disable the filter by code does not work for me anymore.

I cant do antMathchers(/internal/**).addFilterBefore( aadAuthenticationFilter, UsernamePasswordAuthenticationFilter.class );
and a different antMathchers(/external/**).addFilterBefore( new MyFilter(), UsernamePasswordAuthenticationFilter.class );

because the aadAuthenticationFilter is always applied (not onli for internal paths)

**Comment by saragluna** [comment]
Sorry for the late response. 

The scenario you described could be handled by put `MyFilter` before `AADAuthenticaionFilter`, which needs code change to the `AADAuthenticationFilter` to skip processing when current context is authenticated. 
We're planning to add such changes and will let you know when it's done.

**Comment by saragluna** [comment]
Created a PR #872  for this.

**Comment by Gaboxondo** [comment]
Thenk you so much @saragluna, I will be aware of changes :)

**Comment by saragluna** [comment]
Closing this issue, [release 2.3.1](https://github.com/microsoft/azure-spring-boot/releases/tag/v2.3.1) already contains this PR and we'll make a release for 2.2.x in weeks.
