### ISSUE TITLE
AADAppRoleStatelessAuthenticationFilter filter tries to Authenticate a token from a different Authentication/Identity Provider

### ISSUE THREAD

**Issue by nikhilingole** [microsoft/azure-spring-boot#871]
Azure Spring Boot starter dependency version 2.2.4
(Also tried with 2.2.0 )

## Environment
- Spring boot starter:
  
  - active directory spring boot starter
  - key vault spring boot starter
  
- OS Type: Windows & Linux
- Java version: 
  - 1.8
  
## Summary
AADAppRoleStatelessAuthenticationFilter attempts to Authenticate a jwt token from another Identity Provider and fails. 
We need to support 2 Identity providers in our App. Azure AD and an in-house one.
Both the filters work as expected when used individually but AAD filter fails when used in combination. 

## Reproduce steps
1. I create a Config class and added both the filters in the chain.

        @Autowired
        private AADAppRoleStatelessAuthenticationFilter aadAuthFilter;

        @Autowired
        private VaisAuthenticationFilter vaisAuthFilter;

        @Override
        protected void configure(HttpSecurity http) throws Exception {
        http.httpBasic().disable();
        http.formLogin().disable();

        http.authorizeRequests().antMatchers("/").permitAll();
        http.authorizeRequests().antMatchers("/uap/**").authenticated();
        http.authorizeRequests().antMatchers("/actuator/**").permitAll();

        http.csrf().disable().sessionManagement().sessionCreationPolicy(SessionCreationPolicy.STATELESS);

        http.addFilterBefore(aadAuthFilter, UsernamePasswordAuthenticationFilter.class);
        http.addFilterBefore(vaisAuthFilter, AADAppRoleStatelessAuthenticationFilter.class);
     

2. Add these properties to Azure Key Vault (including others)
        azure.activedirectory.session-stateless=true
        azure.activedirectory.client-id=xxxxxxx

3. Generate the  jwt-Token from our In-house (VAIS) Identity provider and send it with the Request.

## Expected Results
The VAIS Auth filter should verify the token -- **It does**
The AADAppRoleStatelessAuthenticationFilter should ignore the token since it is not issued by AAD or not fail. There should be a way to configure if a token should be validated by AADAppRoleStatelessAuthenticationFilter or the implementation
[AADFilterStackTrace.txt](https://github.com/microsoft/azure-spring-boot/files/4516960/AADFilterStackTrace.txt)
 should have it.

The VAIS filter does set the SecurityContext if the token is valid according to it.
        ` Authentication authentication = new PreAuthenticatedAuthenticationToken(jwtToken, null, null);
                authentication.setAuthenticated(true);
                SecurityContextHolder.getContext().setAuthentication(authentication);`

And it does not validate the token if the issuer is AAD.

## Actual Results
After the VaisAuthenticationFilter is done validating the token, AADAppRoleStatelessAuthenticationFilter also tries to validate the same token and fails with the following error.

`
com.nimbusds.jose.proc.BadJOSEException: Signed JWT rejected: Another algorithm expected, or no matching key(s) found
	at com.nimbusds.jwt.proc.DefaultJWTProcessor.<clinit>(DefaultJWTProcessor.java:99) ~[nimbus-jose-jwt-7.9.jar:7.9]
	at niks.playground.security.VaisTokenVerifier.getJwtProcessor(VaisTokenVerifier.java:88) ~[classes/:na]
	at niks.playground.security.VaisTokenVerifier.verifyToken(VaisTokenVerifier.java:78) ~[classes/:na]
	at niks.playground.security.VaisTokenVerifier.verifyToken(VaisTokenVerifier.java:61) ~[classes/:na]
	at niks.playground.security.VaisAuthenticationFilter.doFilterInternal(VaisAuthenticationFilter.java:67) ~[classes/:na]
	at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:119) [spring-web-5.2.5.RELEASE.jar:5.2.5.RELEASE]`

**Is there any workaround to this or any recommended approach for scenarios like this.**

Thanks.

**Comment by saragluna** [comment]
Created a PR to handle such scenario #872.

**Comment by nikhilingole** [comment]
@saragluna  - Thanks for considering this. 
Any idea on what release this would be part of and when it would be GA.

**Comment by saragluna** [comment]
Sorry for the late response, we've already released it in our version [2.3.1](https://github.com/microsoft/azure-spring-boot/releases/tag/v2.3.1), but there's no release for Spring Boot 2.2.x yet, we'll make a release for 2.2.x in weeks according to our release plan.

**Comment by chenrujun** [comment]
Closing this issue.
Because it's not active for a long time.
If anyone have similar issue, please create issue in new repo: https://github.com/Azure/azure-sdk-for-java/issues
