### ISSUE TITLE
cosmosdb - context load fail due to "Input byte array has incorrect ending byte at 88"

### ISSUE THREAD

**Issue by Paizo** [microsoft/azure-spring-boot#925]
## Environment
- Spring boot starter:
  - cosmosdb spring boot starter  
- OS Type: Windows
- Java version: 
  - 1.8
  
## Summary
Following the examples at https://docs.microsoft.com/en-us/azure/developer/java/spring-framework/how-to-guides-spring-data-cosmosdb the resulting application does not start

## Reproduce steps

A repo to reproduce the issue is available here: https://github.com/Paizo/spring-cosmosdb

add the cosmos starter dependency
create a bean annotated with @Document and repository extending CosmosRepository
@EnableCosmosRepositories 

The use of a custom CosmosDBConfig does not change change the result

start the application or mvn clean install

## Expected Results

The application to start or at least get to the next error when connecting to the database

## Actual Results

**Caused by: java.lang.IllegalArgumentException: Input byte array has incorrect ending byte at 88**

```
Caused by: org.springframework.beans.BeanInstantiationException: Failed to instantiate [com.microsoft.azure.spring.data.cosmosdb.core.CosmosTemplate]: Factory method 'cosmosTemplate' threw exception; nested exception is java.lang.IllegalArgumentException: Input byte array has incorrect ending byte at 88
	at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:185) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	at org.springframework.beans.factory.support.ConstructorResolver.instantiate(ConstructorResolver.java:651) ~[spring-beans-5.2.6.RELEASE.jar:5.2.6.RELEASE]
	... 71 common frames omitted
Caused by: java.lang.IllegalArgumentException: Input byte array has incorrect ending byte at 88
	at java.util.Base64$Decoder.decode0(Base64.java:742) ~[na:1.8.0_241]
	at java.util.Base64$Decoder.decode(Base64.java:526) ~[na:1.8.0_241]
	at com.azure.data.cosmos.internal.BaseAuthorizationTokenProvider.getMacInstance(BaseAuthorizationTokenProvider.java:251) ~[azure-cosmos-3.7.3.jar:na]
	at com.azure.data.cosmos.internal.BaseAuthorizationTokenProvider.<init>(BaseAuthorizationTokenProvider.java:36) ~[azure-cosmos-3.7.3.jar:na]
	at com.azure.data.cosmos.internal.RxDocumentClientImpl.<init>(RxDocumentClientImpl.java:200) ~[azure-cosmos-3.7.3.jar:na]
	at com.azure.data.cosmos.internal.RxDocumentClientImpl.<init>(RxDocumentClientImpl.java:135) ~[azure-cosmos-3.7.3.jar:na]
	at com.azure.data.cosmos.internal.RxDocumentClientImpl.<init>(RxDocumentClientImpl.java:124) ~[azure-cosmos-3.7.3.jar:na]
	at com.azure.data.cosmos.internal.AsyncDocumentClient$Builder.build(AsyncDocumentClient.java:177) ~[azure-cosmos-3.7.3.jar:na]
	at com.azure.data.cosmos.CosmosClient.<init>(CosmosClient.java:54) ~[azure-cosmos-3.7.3.jar:na]
```

**Comment by yiliuTo** [comment]
Thanks for the reporting, we will look into it.

**Comment by yiliuTo** [comment]
Hi @Paizo , I have downloaded your sample and replaced the values inCosmosConfiguration.java, and I can see this application run normally. Would you please check if the property file has been filled correctly, such as no more spaces or other symbols behined the values?

**Comment by Paizo** [comment]
Hi @yiliuTo you are right it was an oversight by me, the key has trailing characters at the end.
